name: Build Mubitt APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Create local.properties
      run: |
        cd android
        echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" > local.properties
        echo "DEV_BASE_URL=http://10.0.2.2:8000/" >> local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build Debug APK
      run: |
        cd android
        ./gradlew assembleDebug --stacktrace

    - name: Build Release APK
      run: |
        cd android
        ./gradlew assembleRelease --stacktrace

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: mubitt-debug-apk
        path: android/app/build/outputs/apk/debug/*.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: mubitt-release-apk
        path: android/app/build/outputs/apk/release/*.apk

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Mubitt Release v1.0.${{ github.run_number }}
        body: |
          🎆 **Mubitt Release Automática**

          ## ✅ Compilación Exitosa
          - **Debug APK**: Lista para testing
          - **Release APK**: Lista para distribución beta

          ## 🚀 Características Incluidas
          - 14 pantallas completas con UI/UX premium
          - Búsqueda inteligente específica para San Juan
          - Google Maps integrado y funcional
          - Sistema de pagos completo (efectivo, MercadoPago)
          - Arquitectura Clean + MVVM + Material 3

          ## 📱 Instalación Beta Testing
          1. Descargar APK desde Assets
          2. Habilitar "Orígenes desconocidos" en Android
          3. Instalar y probar en San Juan

          **🎯 Lista para competir con Uber/Didi en San Juan**
        files: |
          android/app/build/outputs/apk/debug/*.apk
          android/app/build/outputs/apk/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
