name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Create local.properties
      run: |
        echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" > android/local.properties
        echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties
    
    - name: Make gradlew executable
      run: chmod +x android/gradlew
    
    - name: Validate Gradle Wrapper
      run: |
        cd android
        ./gradlew --version
    
    - name: Clean all Gradle caches
      run: |
        cd android
        ./gradlew clean --no-daemon
        rm -rf ~/.gradle/caches/modules-*/
        rm -rf ~/.gradle/caches/*/kotlin-dsl/
    
    - name: Check Kotlin and KSP versions
      run: |
        cd android
        ./gradlew dependencies --configuration ksp | head -20 || true
    
    - name: Build Debug APK
      run: |
        cd android
        ./gradlew assembleDebug --stacktrace --info --no-daemon --refresh-dependencies
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mubitt-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk